// Generated by CoffeeScript 1.8.0
(function() {
  var characters, person, _i, _len;

  characters = ['Marty', 'Doc', 'Biff'];

  for (_i = 0, _len = characters.length; _i < _len; _i++) {
    person = characters[_i];
    if (person !== 'Biff') {
      console.log("Get %s to the time machine", person);
    }
  }

}).call(this);
